function [NU,NL,CK,KN,NS,AT,RN,RB,ZE,RO,DC,DI,DF] = setMainStratUnits
% function to only define which subunits belong to which main units
% Main stratigrafic units set according to Dutch Stratigrafic Nomenclature
% https://www.dinoloket.nl/stratigrafische-nomenclator
% and in accordance with the top depth maps available on 
% https://www.nlog.nl/dgm-diep-v5-en-offshore

% Upper-North Sea
NU = {'Oosterhout Formation','Upper North Sea Group'};
% North Sea Super group
NL = {'Basal Dongen Tuffite Member','Basal Dongen Tuffite Member/Lower Germanic Trias Group/Limburg Groep',...
    'Basal Dongen Tuffite Member/Vlieland Sandstone Formation/Lower Buntsandstein Formation',...
    'Brussel Sandstone/Dongen Formation'};
% Chalk
CK = {'Chalk Group','Ekofisk Formation','Ommelanden Formation'};
% Rijnland
KN = {'Bentheim Sandstone Member','De Lier Member','Friesland Member',...
    'Helder Member','Holland Greensand Member/Berkel Sandstone Member/Delfland Subgroup/De Lier Member',...
    'Holland Greensand Member/De Lier Member','IJsselmonde Sandstone Member/upper Bunter unit',...
    'Holland Greensand Member/Main Buntsandstein Subgroup/De Lier Member', ...
    'Holland Greensand Member/IJsselmonde Sandstone Member/Alblasserdam Member/De Lier Member',...
    'IJsselmonde Sandstone Member/Holland Greensand Member/Alblasserdam Member/De Lier Member',...
    'IJsselmonde Sandstone Member/Holland Greensand Member/Basal Dongen Sand Member/Alblasserdam Member/De Lier Member',...
    'Kotter Member','Nieuwerkerk Formation','Rijn Member','Rijn Member/Delfland Subgroup',...
    'Rijnland Group','Rijnland Group/Lower Volpriehausen Sandstone Member',...
    'Rijnland Group/middle Bunter sandstone','Rijswijk Member','Rijswijk Member/De Lier Member',...
    'Rijswijk Member/Delfland Subgroup','Rijswijk Member/Delfland Subgroup/Main Buntsandstein Subgroup',...
    'Rodenrijs Claystone Member/Rijswijk Member','Vlieland Sandstone Formation',...
    'Vlieland Sandstone Formation/Delfland Subgroup',...
    'Vlieland Sandstone Formation/Slochteren Formation/Z2 Carbonate Member/Z3 Main Anhydrite Member',...
    'Vlieland Sandstone Formation/Upper Rotliegend Group','Vlieland Sandstone Formation/Z2 Carbonate Member',...
    'Friesland Member/Z2 Carbonate Member','Friesland Member/Slochteren Formation',...
    'Vlieland Sandstone Formation/Z2 Carbonate Member/Upper Rotliegend Group',...
    'Vlieland subgroup/Main Buntsandstein Subgroup',...
    };
% Nedersaksen and Schieland
NS = {'Bloemendaal Member/Aerdenhout Member/Kotter Member','Central Graben Subgroup',...
    'Delfland Subgroup','Delfland Subgroup/Main Buntsandstein Subgroup',...
    'Friese Front Formation','Lower Graben Formation','Scruff Greensand Formation',...
    'Scruff Greensand Formation/Lower Graben Formation',...
    'Scruff Greensand Formation/Terschelling Sandstone Member',...
    'Scruff Greensand Formation/Zechstein caprock','Scruff Spiculite Member',...
    'Terschelling Sandstone Member','Upper Graben Formation/Central Graben Subgroup',...
    };
% Altena
AT = {'Brabant Formation/Middle Werkendam Member/upper Bunter unit','Middle Werkendam Member',...
    'Middle Werkendam Member/Rijswijk Member/Delfland Subgroup',...
    };
% Upper-Germanic Triassic
RN = {'Rot Formation','Rot Formation/Main Buntsandstein Subgroup','Solling Fat Sandstone member',...
    'Solling Formation',...
    };
% Lower-Germanic Triassic
RB = {'Detfurth Formation','Lower Germanic Trias Group',...
    'Lower Germanic Trias Group/Slochteren Formation/Basal Solling Sandstone Member',...
    'Lower Germanic Trias Group/Slochteren Formation/Z3 Carbonate Member',...
    'Lower Germanic Trias Group/Upper Slochteren Member','Lower Volpriehausen Sandstone Member',...
    'Lower Volpriehausen Sandstone Member/Lower Detfurth Sandstone Member/Hardegsen Formation/Main Buntsandstein Subgroup',...
    'Lower Volpriehausen Sandstone Member/Lower Detfurth Sandstone Member/Solling Fat Sandstone member/Hardegsen Formation',...
    'Lower Volpriehausen Sandstone Member/Lower Slochteren Member',...
    'Lower Volpriehausen Sandstone Member/Upper Rotliegend Group/Z3 Carbonate Member',...
    'Lower Volpriehausen Sandstone Member/Volpriehausen Formation/Volpriehausen Clay-Siltstone Member',...
    'Main Buntsandstein Subgroup','Main Buntsandstein Subgroup/Z3 Carbonate Member',...
    'middle Bunter sandstone','middle Bunter sandstone/Ommelanden Formation',...
    'middle Bunter sandstone/Rot Formation','middle Bunter sandstone/upper Bunter unit',...
    'middle Bunter sandstone/Upper Rotliegend Group/Rijswijk Member',...
    'Slochteren Formation/Main Buntsandstein Subgroup',...
    'Slochteren Formation/Volpriehausen Formation/Z3 Carbonate Member/Z2 (Stassfurt) Formation',...
    'Slochteren Formation/Z3 Carbonate Member/Main Buntsandstein Subgroup',...
    'upper Bunter unit','upper Bunter unit/Upper Rotliegend Group/Main Buntsandstein Subgroup',...
    'Upper Germanic Trias Group','Vlieland Claystone Formation/middle Bunter sandstone',...
    'Volpriehausen Formation','Volpriehausen Formation/Upper Rotliegend Group/Z3 Carbonate Member',...
    'Volpriehausen Formation/Z4 Fringe Sandstone Member',...
    'Volpriehausen Formation/Zechstein Group/Upper Rotliegend Group',...
    'Z3 Carbonate Member/Main Buntsandstein Subgroup',...
    }; 
% Zechstein
ZE = {'Hospital Ground Formation/Zechstein Group',...
    'Limburg Groep/Z2 Carbonate Member',...
    'Limburg Groep/Z2 Carbonate Member/Muschelkalk Formation/Z3 Carbonate Member',...
    'Limburg Groep/Z2 Carbonate Member/Upper Rotliegend Group','Limburg Groep/Zechstein Group',...
    'Slochteren Formation/Z2 Carbonate Member','Slochteren Formation/Z3 Carbonate Member',...
    'Slochteren Formation/Zechstein Group','Upper Slochteren Member/Zechstein Group',...
    'Z1 Carbonate Member/Limburg Groep/Zechstein Group','Z1 Fringe Carbonate Member',...
    'Z1 Fringe Sandstone Member','Z2 (Stassfurt) Formation','Z2 Carbonate Member',...
    'Z2 Carbonate Member/Limburg Groep','Z2 Carbonate Member/Upper Rotliegend Group',...
    'Z2 Carbonate Member/Z3 Carbonate Member','Z3 Carbonate Member',...
    'Z4 (Aller) Formation/Z2 Carbonate Member/Limburg Groep','Zechstein Group',...
    'Zechstein Group/Upper Rotliegend Group',...
    };
% Rotliegend 
RO = {'Limburg Groep/Upper Rotliegend Group',...
    'Lower Slochteren Member','Slochteren Formation','Slochteren Formation/Ten Boer Member',...
    'Slochteren Formation/Ten Boer Member/Akkrum Sandstone member','Ten Boer Member',...
    'Upper Rotliegend Group','Upper Slochteren Member','Upper Slochteren Member/Lower Slochteren Member',...
    'Upper Slochteren Member/Slochteren Formation','Upper Rotliegend Group/Z3 Carbonate Member',...
    };
% Carboniferous
DC = {'Botney Member','De Lutte Formation','Hospital Ground Formation',...
    'Hospital Ground Formation/Lower Slochteren Member',...
    'Klaverbank Formation','Limburg Groep','Limburg Groep/Lower Slochteren Member',...
    'Lower Slochteren Member/Step Graben Formation','Millstone Grit Formation',...
    'Tubbergen Formation',...
    };
DI = {'Dinantian'};
DF = {'Not public',''};

end